version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
  pre_build:
    commands:
      - echo Pre-build started on `date`
  build:
    commands:
      - echo Build started on `date`
      - git submodule update --init --recursive
      - npm config set @dtwebservices:registry="https://api.bintray.com/npm/bloomberg/gigwork///"
      - cd pybossa/themes/default/static/src && yarn && webpack
  post_build:
    commands:
      - rm -rf node_modules
      - echo Build completed on `date`
artifacts:
  files:
    - pybossa/**/*
    - appspec.yml
    - scripts/*
